seed: 2017
root_dir: ./exp
run_name: nafnet-base

model:
    batch_size: 4
    num_machine: 1
    num_worker: 8
    save_freq: !!float 5e3
    iteration: !!float 2e5
    resume:
        state: ~
    optim:
        name: adam
        param:
            lr: 2.e-4
            weight_decay: 0.
            betas: [0.9, 0.99]
    schedule:
        name: CosineAnnealingLR
        param:
            T_max: 640000
            eta_min: 1.e-7

data:
    train:
        name: PairDataSet
        param:
            lq_path: ~
            hq_path: ~
            down_scale: 1
            patch_size: 128
            aug_mode: ['flip', 'rot']
            read_mode: lmdb
    test:
        name: PairDataSet
        param:
            lq_path: ~
            hq_path: ~
            down_scale: 1
            patch_size: -1
            aug_mode: ~
            read_mode: lmdb

arch:
    net_g:
        name: NAFNet
        param:
            in_ch: 3
            num_feats: 64
            mid_blk_nums: 12
            enc_blk_nums: [2, 2, 4, 8]
            dec_blk_nums : [2, 2, 2, 2]
            blk_params:
                DW_Expand: 2
                FFN_Expand: 2
                drop_rate: 0.


loss:
    l1:
        weight: 1.
        reduction: mean
    mse:
        weight: 2.
        reduction: mean


metric:
    psnr_rgb:
        crop_border: 0
        input_order: CHW
        test_y_channel: False
    ssim_rgb:
        crop_border: 0
        input_order: CHW
        test_y_channel: False




