seed: 2017
root_dir: results
run_name: VEModelPretrain-SSCT-Test


model:
    name: VEModelPretrain
    num_nodes: 1
    train_freq: 50
    test_freq: 2000
    save_freq: !!float 5e3
    iteration: !!float 8e5
    gradient_accumulation: 1

    best_metric: 
        name: psnr_rgb
        value: 26

    loader:
        train:
            batch_size: 4
            shuffle: True
            num_workers: 2
        test:
            batch_size: 1
            shuffle: False
            num_workers: 2

    optim:
        name: AdamW
        param:
            lr: 2.e-4
            weight_decay: 0.
            betas: [0.9, 0.99]

    schedule:
        name: cosine
        num_warmup_steps: 0
        num_training_steps: !!float 8e5

data:
    train:
        name: SimuteNIDDGaussian
        param:
            hq_path: /data/dataset/low_level/wed_data/
            length: 320000
            patch_size: 128
            augment: true
            sigma_min: 10
            sigma_max: 75
            sigma_iid: [10, 25, 30, 40, 50, 70, 75]
    test:
        name: VDNSimuTest
        param:
            lmdb_path: /data/dataset/low_level/test_dataset/NiidGauss/CBSD68_allcase.lmdb

arch:
    name: VEMIDNetPreTrain
    noise_est_param:
        in_ch: 3
        num_groups: [4, 3, 2]
        num_feats: 32
        head_dim_s: 32
        head_num_c: 4
        winsize: 8
        mlp_ratio_s: 4
        mlp_ratio_c: 4
        drop_rate: 0.1
        bias: False
        pool: False
        pool_mode: conv
        blk_name: ssct
    noise_rm_param:
        in_ch: 3
        num_feats: 32
        num_enc_blk: [2, 2, 2]
        num_mid_blk: 2
        num_dec_blk: [2, 2, 2]
        blk_name : ssct
        blk_param :
            head_dim_s: 32
            head_num_c: 4
            winsize: 8
            mlp_ratio_s: 2
            mlp_ratio_c: 2
            drop_prob_s: 0.02
            drop_prob_c: 0.02
            bias: False
            pool: False
            pool_mode: conv
            shortcut_prob: 0.01

loss:
    mse:
        weight: 1.
        reduction: mean


metric:
    psnr_rgb:
        crop_border: 0
        input_order: HWC
        test_y_channel: False
    ssim_rgb:
        crop_border: 0
        input_order: HWC
        test_y_channel: False