seed: 2017
root_dir: results
run_name: pretrian_vdn


model:
    name: VEMModel
    num_nodes: 1
    train_freq: 50
    test_freq: 2000
    save_freq: !!float 5e3
    iteration: !!float 4e5
    gradient_accumulation: 1

    best_metric: 
        name: psnr_rgb
        value: 26

    loader:
        train:
            batch_size: 64
            shuffle: True
            num_workers: 8
        test:
            batch_size: 1
            shuffle: False
            num_workers: 2

    optim:
        name: AdamW
        param:
            lr: 2.e-4
            weight_decay: 0.
            betas: [0.9, 0.99]

    schedule:
        name: cosine
        num_warmup_steps: 0
        num_training_steps: !!float 4e5


data:
    train:
        name: SimuteNIDDGaussian
        param:
            hq_path: /data/dataset/low_level/wed_data/
            length: 320000
            patch_size: 128
            augment: true
            sigma_min: 10
            sigma_max: 70
            sigma_iid: [10, 25, 30, 40, 50, 70, 75]
    test:
        name: VDNSimuTest
        param:
            lmdb_path: /data/dataset/low_level/test_dataset/NiidGauss/CBSD68_allcase.lmdb

arch:
    name: VEMDNet
    pretrian_dncnn: True
    pretrain_unet: False
    pretrain: /data/workspace/master_paper/PictoRestore/results/VDN-WED-Est2/best_ckpt/best_375001.pth

loss:
    PSNRLoss:
        weight: 1.
        reduction: mean
        toY: False


metric:
    psnr_rgb:
        crop_border: 0
        input_order: HWC
        test_y_channel: False
    ssim_rgb:
        crop_border: 0
        input_order: HWC
        test_y_channel: False