seed: 10
root_dir: results
run_name: nafnet-sidd-wf32-CVData


model:
    name: StandardModel
    num_nodes: 1
    train_freq: 50
    test_freq: 5000
    save_freq: !!float 5e3
    iteration: !!float 4e5
    gradient_accumulation: 1

    best_metric: 
        name: psnr_rgb
        value: 30

    loader:
        train:
            batch_size: 4
            shuffle: True
            num_workers: 2
        test:
            batch_size: 1
            shuffle: False
            num_workers: 2

    optim:
        name: AdamW
        param:
            lr: 1.e-3
            weight_decay: 0.
            betas: [0.9, 0.9]

    schedule:
        name: CosineAnnealingLR
        T_max : 3200000 # 单卡 4e5 x 8 (gpu个数)
        eta_min : 1.e-7

data:
    train:
        name: SIDDPairDataset
        param:
            lq_path: /data/dataset/low_level/sidd_tmp//train_noisy.lmdb
            hq_path: /data/dataset/low_level/sidd_tmp//train_gt.lmdb
            patch_size: 256
            scale: 1
            flip: False
            rotation: False
            read_mode: lmdb
    test:
        name: SIDDPairDataset
        param:
            lq_path: /data/dataset/low_level/sidd_tmp//val_noisy.lmdb
            hq_path: /data/dataset/low_level/sidd_tmp//val_gt.lmdb
            read_mode: lmdb

arch:
    name: NAFNet
    in_ch: 3
    num_feats: 32
    mid_blk_nums: 12
    enc_blk_nums: [2, 2, 4, 8]
    dec_blk_nums : [2, 2, 2, 2]
    blk_name: nafnet
    blk_params:
        DW_Expand: 2
        FFN_Expand: 2
        drop_rate: 0.

loss:
    PSNRLoss:
        weight: 1.
        reduction: mean
        toY: False


metric:
    psnr_rgb:
        crop_border: 0
        input_order: HWC
        test_y_channel: False
    ssim_rgb:
        crop_border: 0
        input_order: HWC
        test_y_channel: False