seed: 10
exp_dir: results
run_name: nafnet-sidd-wf32-PSNRLoss

hyparams:
    batch_size: 32 # num_gpus x num_nodes x batch_size_per_gpu
    init_lr: 2.e-4
    patch_size: 238
    optim_name: Adam
    optim_weight_decay: 0.
    optim_beta_1: 1
    optim_beta_2: 1
    schedule_name: cosine
    schedule_num_warmup: 200
    schedule_num_train: 640000

model:
    name: BaseModel
    num_nodes: 1
    batch_size: 4
    num_worker: 8
    val_freq: !!float 2e3
    save_freq: !!float 5e3
    iteration: !!float 4e5
    best_metric: psnr_rgb
    gradient_accumulation: 1
    is_eval_ddp: True
    optim:
        name: AdamW
        param:
            lr: 1.e-3
            weight_decay: 0.
            betas: [0.9, 0.9]
    schedule:
        name: cosine
        num_warmup_steps: 0
        num_training_steps: !!float 4e5

data:
    train:
        name: PairDataset
        param:
            lq_path: /data/dataset/low_level/sidd/train_noisy.lmdb
            hq_path: /data/dataset/low_level/sidd/train_gt.lmdb
            down_scale: 1
            patch_size: 256
            aug_mode: ~
            read_mode: lmdb
    test:
        name: PairDataSet
        param:
            lq_path: /data/dataset/low_level/sidd/val_noisy.lmdb
            hq_path: /data/dataset/low_level/sidd/val_gt.lmdb
            down_scale: 1
            patch_size: -1
            aug_mode: ~
            read_mode: lmdb

arch:
    net_g:
        name: NAFNet
        param:
            in_ch: 3
            num_feats: 32
            mid_blk_nums: 12
            enc_blk_nums: [2, 2, 4, 8]
            dec_blk_nums : [2, 2, 2, 2]
            blk_params:
                DW_Expand: 2
                FFN_Expand: 2
                drop_rate: 0.

loss:
    PSNRLoss:
        weight: 1.
        reduction: mean
        toY: False


metric:
    psnr_rgb:
        crop_border: 0
        input_order: HWC
        test_y_channel: False
    ssim_rgb:
        crop_border: 0
        input_order: HWC
        test_y_channel: False