seed: 2017
exp_dir: results
run_name: nafnet-base

hyparams:
    batch_size: 32 # num_gpus x num_nodes x batch_size_per_gpu
    init_lr: 2.e-4
    patch_size: 256


model:
    name: BaseModel
    batch_size: 4
    num_nodes: 1
    num_worker: 8
    val_freq: 2e3
    save_freq: !!float 5e3
    iteration: !!float 2e5
    best_metric: psnr_rgb
    gradient_accumulation: 2
    is_eval_ddp: True

    optim:
        name: AdamW
        param:
            lr: 2.e-4
            weight_decay: 0.
            betas: [0.9, 0.9]
    schedule:
        # Supports torch.optim.lr_scheduler without warmup and diffusers.optimization.get_scheduler with warmup
        # diffusers.optimization with warmup
        # Note: The step count is defined per GPU.

        # name: cosine
        # num_warmup_steps: 0
        # num_training_steps: !!float 4e5

       # When using torch.optim.lr_scheduler without warmup,
       # remember that the step count must account for the number of GPUs in use.
        name: CosineAnnealingLR
        T_max : 3200000 # 4e5 x 8 (the number of gpus)
        eta_min : 1.e-7

data:
    train:
        name: PairDataSet
        param:
            lq_path: hello
            hq_path: hello
            down_scale: 1
            patch_size: 128
            aug_mode: ['flip', 'rot']
            read_mode: lmdb
    test:
        name: PairDataSet
        param:
            lq_path: hello
            hq_path: hello
            down_scale: 1
            patch_size: -1
            aug_mode: hello
            read_mode: lmdb

arch:
    net_g:
        name: NAFNet
        param:
            in_ch: 3
            num_feats: 64
            mid_blk_nums: 12
            enc_blk_nums: [2, 2, 4, 8]
            dec_blk_nums : [2, 2, 2, 2]
            blk_params:
                DW_Expand: 2
                FFN_Expand: 2
                drop_rate: 0.


loss:
    l1:
        weight: 1.
        reduction: mean
    mse:
        weight: 2.
        reduction: mean


metric:
    psnr_rgb:
        crop_border: 0
        input_order: CHW
        test_y_channel: False
    ssim_rgb:
        crop_border: 0
        input_order: CHW
        test_y_channel: False